doc: Update rfc2629.dtd, use local copy, fix error, and fix warning
- I get this warning when building the docs:
WARNING: No DTD given, defaulting to
/usr/lib/python3.7/site-packages/xml2rfc/templates/rfc2629.dtd

- Patching Makefile.am to use the local DTD gives the below error:
ERROR: Unable to validate the XML document: protocol-binary.full
protocol-binary.full: Line 2: Value "trust200902" for attribute ipr of
rfc is not among the enumerated set

- This commit suggests that you prefer to use a local copy of the DTD.
    commit fe2629fd3fcdbde49f4016635866bd3488be88b0
    Author: Steve Wills <steve@mouf.net>
    Date:   Wed Jul 23 19:21:40 2014 +0000

        keep local copies of dtd and use it
        This commit ensures we don't rely on and external site for the docs
        to build.
        If that site were to go away, we wouldn't be able to build docs.

- Hence, update the DTD too.