Fix undefined behavior with -D_FORTIFY_SOURCE=2
When compiling with -D_FORTIFY_SOURCE=2, printf is defined as a macro,
which makes the #ifdef TLS block in the usage() function of memcached.c
undefined behavior.

This warning was caught by compiling with clang:

memcached.c:7829:2: error: embedding a directive within macro arguments has undefined behavior [-Werror,-Wembedded-directive]
^
memcached.c:7832:2: error: embedding a directive within macro arguments has undefined behavior [-Werror,-Wembedded-directive]
^

originally by @tstellar - rewritten by dormando due to a source
conflict and cleanup of some new ifdefs.